// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmhMBgf3qGbM_fGwEs3f5KzG5GuSGHbk',
    appId: '1:384189160427:web:f6ca2903ddf4c5396e57ae',
    messagingSenderId: '384189160427',
    projectId: 'chatapplogin-201cc',
    authDomain: 'chatapplogin-201cc.firebaseapp.com',
    storageBucket: 'chatapplogin-201cc.appspot.com',
    measurementId: 'G-SXBP87GWPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsWjX034ObLou9pMIIZDqsmD1eOxxtSc',
    appId: '1:384189160427:android:9d37c8115d0620566e57ae',
    messagingSenderId: '384189160427',
    projectId: 'chatapplogin-201cc',
    storageBucket: 'chatapplogin-201cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8piNtk_MhsH9zrmVMwm7YYBFhoSJJUbQ',
    appId: '1:384189160427:ios:b05ae90911b228a96e57ae',
    messagingSenderId: '384189160427',
    projectId: 'chatapplogin-201cc',
    storageBucket: 'chatapplogin-201cc.appspot.com',
    iosBundleId: 'com.example.lamieMiddleEastMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8piNtk_MhsH9zrmVMwm7YYBFhoSJJUbQ',
    appId: '1:384189160427:ios:b05ae90911b228a96e57ae',
    messagingSenderId: '384189160427',
    projectId: 'chatapplogin-201cc',
    storageBucket: 'chatapplogin-201cc.appspot.com',
    iosBundleId: 'com.example.lamieMiddleEastMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNmhMBgf3qGbM_fGwEs3f5KzG5GuSGHbk',
    appId: '1:384189160427:web:6a29f91d6fde5a4d6e57ae',
    messagingSenderId: '384189160427',
    projectId: 'chatapplogin-201cc',
    authDomain: 'chatapplogin-201cc.firebaseapp.com',
    storageBucket: 'chatapplogin-201cc.appspot.com',
    measurementId: 'G-23MS0R3QPE',
  );
}
